var il8n = {
	 Import:'导入'
	,ImportOne:'导入单条记录'
	,Export:'导出'
	,ExportOne:'导出单条记录'
	,Name:'名称'
	,ID:'编号'
	,Money:'金币'
	,Credits:'积分'
	,PassWord:'密码'
	,Delete:'删除'
	,Subject:'科目'
	,Title:'标题'
	,Count:{
		 Used:'使用数'
		,Right:'做对数'
		,Wrong:'做错数'
		,GiveUp:'放弃数'
		,User:'用户数'
		,Total:'总数'
	}
	,Score:{
		 Top:'最高分'
		,TopUser:'最高分用户'
		,AVG:'平均分'
	}
	,DoQuiz:'做题'	
	,Operations:'操作'
	,Paper:{
		 Brief:'试卷简要'
		,Paper:'试卷'
		,Result:'成绩结果'
	}
	,Submit:'提交'
	,Navigation:'导航'
	,Clock:'时钟'
	,User:{
		 Name:'用户名'
		,PassWord:'密码'		
		,Login:'登录'
		,Group:'用户组'
		,User:'用户'
	}
	,CAPTCHA:'验证码'
	,ReCAPTCHA:'刷新验证码'
	,CheckCAPTCHA:'输入验证码'
	,Loading:'读取中'
	,Wait:'等待'
	,Error:'错误'
	,WhyImWrong:{
		 Title:'做错原因'
		,NotGoodEnough:'是我还没学好'
		,Carelese:'我太粗心了'
		,IHaveNoIdea:'错的莫名其妙...'
		,WrongAnswer:'答案错了,我没有错'
		,Stat:'统计结果'
	}
	,Question:'题目'
	,TimeLimit:'时间限制'
	,Score:{
		 Top:'最高分'
		,TopUser:'最高分得主'
		,Avg:'平均分'
		,Score:'分数'
		,Total:'总分'
	}
	,Menu:'菜单'
	,Yes:'是'
	,No:'不是'
	,Privilege:'权限'
	,Subject:'科目'
	,Wrongs:'错题本'
	,DateCreated:'创建时间'
	,Weight:'权重'
	,Description:'说明'
	,WeLikeStudy:'我们喜欢学习!'
	,Log:'日志'
	,Review:'查看'
	,Proportion:'对错率'
	,Application:'应用'
	,WhyNotIE6:'<div style="font-size:20px"><p>检测到您浏览器的内核采用的是IE6,系统会非常慢.</p>' +
			'<p>如果您用的是<b>搜狗浏览器,遨游浏览器,腾讯TT浏览器,360浏览器</b>,这都是一样的.<br/>' +
			'因为他们都是IE内核包装的' +
			'<p>强烈建议您选用谷歌浏览器或火狐浏览器,升级IE6到IE8也是一种方案,这样系统会快很多</p></div>'
	,YouAreIE6:'您浏览器的内核是IE6'
	
};