var il8n = {
	 Import:'导入'
	,Export:'导出'
	,Name:'名称'
	,ID:'编号'
	,Money:'金币'
	,Credits:'积分'
	,PassWord:'密码'
	,Delete:'删除'
	,Subject:'科目'
	,Title:'标题'
	,Count:{
		 Used:'使用数'
		,Right:'做对数'
		,Wrong:'做错数'
		,GiveUp:'放弃数'
		,User:'用户数'
	}
	,Score:{
		 Top:'最高分'
		,TopUser:'最高分用户'
		,AVG:'平均分'
	}
	,DoQuiz:'做题'	
	,Operations:'操作'
	,Paper:{
		 Brief:'试卷简要'
		,Paper:'试卷'
	}
	,Submit:'提交'
	,Navigation:'导航'
	,Clock:'时钟'
	,User:{
		 Name:'用户名'
		,PassWord:'密码'		
		,Login:'登录'
		,Group:'用户组'
	}
	,CAPTCHA:'验证码'
	,ReCAPTCHA:'刷新验证码'
	,CheckCAPTCHA:'输入验证码'
	,Loading:'读取中'
	,Wait:'等待'
	,Error:'错误'
	,WhyImWrong:{
		 Title:'做错原因'
		,NotGoodEnough:'是我还没学好'
		,Carelese:'我太粗心了'
		,IHaveNoIdea:'错的莫名其妙...'
		,WrongAnswer:'答案错了,我没有错'
		,Stat:'统计结果'
	}
	,Question:'题目'
	,TimeLimit:'时间限制'
	,Score:{
		 Top:'最高分'
		,TopUser:'最高分得主'
		,Avg:'平均分'
	}
	,Menu:'菜单'
	,Yes:'是'
	,No:'不是'
	,Privilege:'权限'
	,Subject:'科目'
	
};